apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dev  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-dev
  template:
    metadata:
      labels:
        app: backend-dev
    spec:
      containers:
        - name: backend-dev
          image: 975050178905.dkr.ecr.us-east-1.amazonaws.com/insiderhub-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: "production"
            - name: HTTP_PORT
              value: "8080"
            - name: TOKEN_SECRET
              value: "s6u6jq3-Z5dn]H8}"
            - name: JWT_SECRET
              value: "6c5e9f88f5d432fb905dabfc8dd88c408c19c3f74aa5b6f6"
            - name: MONGO_URI
              value: "mongodb+srv://chamikab:dxyGtRzOu5scv9Kc@fanso.4iystgm.mongodb.net/fanso?retryWrites=true&w=majority&appName=fanso"
            - name: REDIS_HOST
              value: "redis.default.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
            - name: REDIS_PREFIX
              value: "bee_queue"
            - name: DOMAIN
              value: "https://api.dev.inrcliq.com"
            - name: BASE_URL
              value: "https://api.dev.inrcliq.com"
            - name: USER_URL
              value: "https://dev.inrcliq.com"
            - name: TEMPLATE_DIR
              value: "templates"
            - name: MAILER_CONCURRENCY
              value: "1"
            - name: EMAIL_VERIFIED_SUCCESS_URL
              value: "https://example.com/auth/email-verified-success"
            - name: HASH_PW_CLIENT
              value: "false"
          volumeMounts:
            - name: api-public
              mountPath: /app/public
      volumes:
      - name: api-public
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: backend-dev
  annotations:    
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:975050178905:certificate/c7bd3a85-6a91-48e9-8999-19587aab554a"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  selector:
    app: backend-dev
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080