version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: srilankan_gov_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: srilankan_gov_services
    volumes:
      - mongodb_data:/data/db
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  # Redis for caching and sessions
  redis:
    image: redis:7.2-alpine
    container_name: srilankan_gov_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  # Backend API
  backend:
    build: 
      context: ./user_backend
      dockerfile: Dockerfile
    container_name: srilankan_gov_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/srilankan_gov_services?authSource=admin
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-here
      JWT_REFRESH_SECRET: your-super-secret-refresh-key-here
      BCRYPT_ROUNDS: 12
      CORS_ORIGIN: http://localhost:3001
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./user_backend:/app
      - /app/node_modules
    networks:
      - app-network

  # Web Admin Panel
  web_admin:
    build:
      context: ./user_web
      dockerfile: Dockerfile
    container_name: srilankan_gov_web
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      REACT_APP_API_URL: http://localhost:3000
      REACT_APP_WS_URL: ws://localhost:3000
      CHOKIDAR_USEPOLLING: true
    depends_on:
      - backend
    volumes:
      - ./user_web:/app
      - /app/node_modules
    networks:
      - app-network

volumes:
  mongodb_data:
  redis_data:

networks:
  app-network:
    driver: bridge