version: '3.8'

services:
  backend:
    environment:
      - NODE_ENV=development
    volumes:
      - ./user_backend:/app
      - ./shared:/app/node_modules/@srilanka-gov/shared
    command: npm run dev
    ports:
      - "${API_PORT}:${API_PORT}"
      - "9229:9229"  # Node.js debug port

  frontend:
    environment:
      - NODE_ENV=development
    volumes:
      - ./user_web:/app
      - ./shared:/app/node_modules/@srilanka-gov/shared
    command: npm start
    ports:
      - "${WEB_PORT}:3000"
      - "19000:19000"  # React Native debug port

  nginx:
    ports:
      - "80:80"