frontend:
  build:
    context: ./frontend
    dockerfile: Dockerfile
  container_name: sri_gov_frontend
  restart: unless-stopped
  volumes:
    - ./frontend:/app
  ports:
    - "19020:19000"  # host:container
    - "19021:19001"
  networks:
    - gov-network
